<?php
$data = [
    [
        'id' => 'simpanan-berjangka',
        'small_title' => 'SIMPANAN BERJANGKA',
        'img' => 'img-content5.jpg',
        'title' => 'Jasa Simpanan Berjangka sewaktu waktu dapat berubah. sesuai dengan kebijakan KSP Dana Jaya Sentosa.',
        'description' => '<p><strong>Prakata</strong>:</p>
<ul><li>MEMBERIKAN JASA TINGCI 2 KALI BUNCA DEPOSITO BANK" <br>KSP Dana Jaya Sentosa adalah Koperasi Tingkat yang berdiri dengan Badan Hukum No.   Koperasi ini fokus bergerak di bidang usaha Simpan Pinjam dengan Ijin dari Kementerian Koperasi & UKM No. Koperasi Simpan Pinjam Dana Jaya Sentosa terdaftar, dibina dan diawasi dengan Nomor Induk Koperasi (NIK) No.   Nomor lnduk Berusaha (NIB) Koperasi ini didirikan untuk meningkatkan kesejahteraan para Anggota khususnya dan masyarakat umumnya.</li><li>"SUMBER DANA" Dana yang dikelola bersumber dari Simpanan Anggota berupa Simpanan Pokok, Simpanan Wajib dan Simpanan Sukarela. Secara khusus, Perusahaan/Koperasi juga mengharapkan Simpanan Sukarela dari Anggota yang ditempatkan sebagai "SIMPANAN BERJANGKA" dengan jangka waktu 1, 3, 6, 12, 24 atau 36 bulan Khusus Simpanan Berjangka Koperasi tersebut diberikan jasa bulanan yang hasilnya jauh lebih besar jika dibandingkan dengan institusi lain.</li><li>"PENYALUR DANA"<br>Dana disalurkan kepada Anggota , Koperasi lain dan atau Anggotanya yang membutuhkan dengan sangat hati-hati, selektif dan dapat dipertanggungjawabkan. Dana yang disalurkan kepada para Anggota diseleksi dengan ketat sehingga kemungkinan macet sangat kecil, dan diutamakan bagi yang sudah karyawan tetap dan penggajian melalui bank (payroll), serta Pinjaman untuk Modal Usaha Anggota.</li><li>KOMITNIEN PENGURUS<br>Pengurus berkomitmen untuk mengelola setiap dana dengan baik dan penuh tanggung jawab , sehingga menguntungkan bagi para Penyimpan , Pemilik Dana serta para Anggota serta semua pihak.</li></ul>
<p><strong>Ketentuan Simpanan Berjangka</strong></p><ul><li>Untuk dapat menempatkan dana scbagai Simpanan di KSP Dana Jaya Sentosa, terlebih dahulu mengisi formulir yang telah tersedia dan memenuhi syarat sebagai Anggota.</li><li>Dana ditempatkan sehagai Simpanan Berjangka Mandiri dcngan jangka waktu I, 3, 6, 12, 24 atau 36 bulan.</li><li>Atas setiap dana yang ditempatkan, diberikan jasa simpanan sebagai berikut : <br>(Berlaku dari 1 Januari 2024)<br></li><li>Jasa diberikan setiap bulan atau sekaligus di akhir periode (bebas memilih).&nbsp;</li><li>Atas Jasa simpanan dikenakan pajak 10 % (Sesuai ketentuan perpajakan yang berlaku untuk koperasi oleh pemerintah). Berbeda dengan Simpanan Bank, pajak 20% (pajak di Koperasi lebih rendah).</li><li>Simpanan boleh dicairkan sebagian atau seluruhnya sebelum jatuh tempo. (Khusus pencairan diatas Rp. 50 Juta diberitahukan 1-2 hari sebelumnya).</li><li>Atas pencairan dana sebelum jatuh tempo tidak dikenakan pinalti. Tetapi jasa kurang dari 1 bulan jasa belum jatuh tempo) tidak dihitung, dan Anggota bawa 2 buah materai.</li><li>Simpanan Berjangka yang sudah jatuh tempo, otomatis diperpanjang kembali 1 periode lagi , kecuali ada pemberitahuan pencairan dana sebehunnya Jasa sesuai yang berlaku saat perpanjangan.</li><li>Setiap dana yang ciisimpan di KSP Dana Jaya Sentosa dijamin man dan dikelola secara profesional oleh Pengurus, Manager dan seluruh staff.</li><li>Sebagai bukti Simpanan, diterbitkan Sertifikat Simpanan Berjangka yang ditandatangani Ketua/Direksi dan dibubuhi materai/stempel KSP Dana Jaya Sentosa. PERCAYAKAN DANA ANDA DIKELOLA DENGAN BAIK OLEH MANAGEMEN KOPERASI SIMPAN PINJAM DANA JAYA SENTOSA, DAN NIKMATI KEUNTUNGAN JASA SETIAP BULAN.</li></ul>
<p></p>',
    ],

    [
        'id' => 'simpanan-pendidikan',
        'small_title' => 'SIMPANAN  PENDIDIKAN',
        'img' => 'img-content4.jpg',
        'title' => 'Pendidikan, Investasi Berharga untuk si Buah Hati',
        'description' => '<ul><li>"Impian Orangtua Mewujudkan cita-cita Putra Putri " <br>Simpanan Berencana Pendidikan ini dirancang untuk wujudkan impian para Orang Tua agar Putra- Putri tercinta meraih sukses di Pendidikan Tinggi/Sarjana. Oleh karena itu sejak dini hams dipersiapkan dana dengan mulai menabung. </li><li>"Masa Depan terbantu"<br>Dungan simpanan hanya Rp. 150.000/bulan, maka dalam tempo 15 Tahun Dana Pendidikan akan terkumpul Rp. 59.935.924,-. Dana tersebut bisa dipakai untuk melanjutkan kuliah si Anak atau modal untuk buka usaha mandiri.</li><li>"Jangka Waktu disesuaikan"<br>Jangka waktu simpanan disesuaikan dengan usia anak. Sehingga jatuh tempo disamakan dengan usia anak tamat SMU. Misalkan usia anak saat ini 2 tahun maka masa simpanan sebaiknya 16 tahun.</li><li>"Setoran Aman"<br>Setoran nap bulan dikirim ke rekening atas nama KSP Dana Jaya Sentosa atau disetor tunai di kantor KSP Dana Jaya Sentosa atau boleh di setor melalui Karyawan Perusahaan yang telah di tunjuk.</li><li>"Dana dikembalikan 100 %"<br>Dalian hal program ini diakhiri sebelum jatuh tempo, maka sanua dana yang disetor dikembalikan 100% berikut jasa yang sudah terkumpul.</li><li>Pervaratan mengilmti Simpanan Berencana Pendidikan:<br>Dirancang khusus untuk Anggota/Calon Anggota dari Koperasi Simpan Pinjam Dana Jaya Sentosa.</li><li>Mengisi Formulir Simpanan dan menyerahkan Copy Akte Kelahiran, KTP Orang Tua dan Kartu Keluarga. <br>Bersedia secara Sukarela untuk menyimpan Darla sesuai yang di sepakati Rp.100.000,- ; Rp.150.000,-; Rp.200.000,- sampai dengan Rp. 1.000.000 per bulan.</li></ul>',
    ],
    [
        'id' => 'simpanan-hari-tua',
        'small_title' => 'SIMPANAN HARI TUA',
        'img' => 'img-content2.jpg',
        'title' => 'Hidup Sejahtera di Hari Tua.',
        'description' => '<ul><li>"PERSIAPAN MEMASUKI HARI Tua"<br>Simpanan Berencana Hari Tua (SHT) ini dirancangkan khsusus untuk Anggota/Calon Anggota KSP Dana Jaya Sentosa yang tujuannya untuk pengadaan dan persiapan memasuki usia hari tua/puma bakti (masa pensiun). Sehingga pada saat tidak lagi bekerja, Anggota/Nasabah memiliki cukup dana/simpanan untuk hari tua.</li><li>"BISA UNTUK USAHA"<br>Dengan simpanan Rp.150.000.-/bulan, maka dalam tempo 15 tahun, Dana Hari Tua akan terkumpul Rp.59.935.924,-. Dana tersebut bisa dipakai untuk modal buka usaha sendiri.</li><li>"JANGKA WAKTU DISESUAIKAN<br>Jangka waktu simpanan disesuaikan dengan usia dari Anggota. Sehingga jatuh temponya disamakan dengan usia perkiraan memasuki hari tut Misalnya usia saat ini 30 tahun, maka simpanan sebaiknya 25 tahun.</li><li>"SETORAN AMAN"<br>Setoran hap bulan dikirim ke rekening atas nama KSP Dana Jaya Sentosa, atau disetor tunai di kantor KSP Dana Jaya Sentosa atau butuh disetor melalui karyawan Perusahaan yang telah di tunjuk.</li><li>"DANA DIKEMBALIKAN 100%"<br>Dalam hal program ini diakhiri sebelum jatuh tempo, maka Semua Dana yang disetor akan dikembalikan 100%, berikut jasa yang sudah terkumpul.</li></ul><p>Persyaratan mengikuti Simpanan Berencana Hari Tua (SHT)</p><ul><li>Dirancang khusus untuk Anggota/Calon Anggota dari Koperasi Simpan Pinjam Dana Jaya Sentosa.</li><li>Mengisi Formulir Simpanan dan menyerahkan Copy KTP orang tua&nbsp;dan Kartu Keluarga</li><li>Bersedia secara Sukarela untuk menyimpan Dana sesuai yang di sepakati yakni Rp.100.000,- ; Rp.150.000,-; Rp.200.000,- sampai dengan Rp. 1.000.000 per bulan.</li><li>Hubungi kami untuk pendaftaran.</li></ul>',
    ],
    [
        'id' => 'simpanan-haji-umron',
        'small_title' => 'SIMPANAN Haji & Umroh',
        'img' => 'haji.jpg',
        'title' => 'Wisata Rohani ke Tanah Suci Bersama KSP. DJS ',
        'description' => '<ul><li>Simpanan yang penarikannya hanya dilakukan pada saat akan melakukan pembayaran/pelunasan ibadah Haji dan umroh</li><li>Penyimpan memilih sendiri biro perjalanan haji dan umroh yang di percaya</li><li>Penyimpan bebas menentukan waktu pelunasan untuk memperoleh nomor porsi haji</li><li>Penyimpan mendaftar sendiri ke departemen agama urusan haji (BPIH) Badan Penyelenggara Ibadah Haji</li><li>KSP. DJS tidak bekerja sama dengan biro perjalanan haji dan umroh manapun </li></ul>
<p>BEBAS BIAYA ADMINISTRASI</p>',
    ],
    [
        'id' => 'simpanan-eksekutif',
        'small_title' => 'SIMPANAN EKSEKUTIF',
        'img' => 'img-content3.jpg',
        'title' => 'Dikhususkan untuk Pejabat / Tokoh Masyarakat',
        'description' => '<p>Dikhususkan untuk Pejabat / Tokoh Masyarakat</p><ul><li>Program ini dirancang Khusus untuk Anggota KSP Dana Jaya Sentosa yang menjadi Eksekutif di Lembaga-lembaga Negara / Pemerintahan/ BUMN dan di tengah tengah masyarakat. Antara lain para Anggota DPR/DPRD, DPD, Gubernur, Walikota/Bupati, Kepala Dinas, Pejabat pejabat Muspida, Tokoh-tokoh Agama, Tokoh -tokoh Adat, Pimpinan-pimpinan Perusahaan dan Badan usaha, para Kepala Sekolah dan para Eksekutif lainnya.</li></ul><p>Persyaratan untuk mengikuti Simpanan Eksekutif</p><ul><li>Terdaftar sebagai Anggota pada KSP Dana Jaya Sentosa.</li><li>Usia masuk 20 s.d 70 tahun.</li><li>Bersedia menabung/simpan rutin setiap bulan.</li><li>Besarnya Simpanan tiap bulan Rp 5.000.000,- atau boleh kelipatan Rp 500.00,- (minimal Rp 2.500.000,- per bulan).</li><li>Peserta Simpanan Eksekutif menerima Buku Anggota, Kartu Anggota dan Buku Simpanan/Mutasi Rekening Simpanan.</li><li>Bila menunggak di atas 6 bulan, maka jasa turun menjadi 10% pertahun.</li></ul><p>Keuntungan menngikuti Simpanan Eksekutif</p><ul><li>Jasa sebesar 13% per tahun (Angka pada tabel sudah potong pajak)</li><li>Saldo dana dilaporkan tiap akhir bulan melalui Surat/SMS/WA/Media Lainnya.</li><li>Dana kelola aman dan profesional dengan hati - hati.</li><li>Saldo dana boleh dipinjam maksimal 90%.</li><li>Dana boleh dicairkan kapan saja sesuai dengan saldo tersedia.</li><li>Bila meninggal dunia dibayarkan Santunan duka Rp 3.000.000,- berikut semua saldo dana dikembalikan.</li></ul><p>Contoh Pada Tabel</p><p>Tuan A seorang Anggota DPRD menabung (simpanan) sebesar Rp 5.000.000,- setiap bulan selama 5 tahun (60 bulan) , Maka pada akhir tahun ke 5, akan menerima total pengembalian Simpanan Rp 300.000.000,- berikut total jasa Rp 105.083.142,- Sehingga total terima bersih Rp&nbsp;&nbsp;405.083.142,-.</p>',
    ],
    [
        'id' => 'simpanan-wirausaha-pasar',
        'small_title' => 'SIMPANAN WIRAUSAHA <br> PASAR',
        'img' => 'market.jpg',
        'title' => 'Simpanan Wirausaha Pasar.',
        'description' => '<ul><li>Simpanan Wirausaha ini dirancang khusus untuk Anggota/Calon Anggota KSP Dana Jaya Sentosa yang tujuannya untuk memiliki dana cukup/simpanan tambahan modal dalam pengembangan Usaha.</li><li>Setoran Simpanan Wirausaha dikirim ke rekening atas nama KSP Dana Jaya Sentosa atau disetor tunai di kantor KSP Dana Jaya Sentosa atau boleh disetor melalui karyawan/petugas yang ditunjuk.</li><li>Dalam hal program ini semua dana yang disetor akan dikembalikan 100% serta jasa yang terkumpul.</li></ul>
<p>Persyaratan mengikuti Simpanan Wirausaha</p><ul><li>Dirancang khusus untuk Anggota/Calon Anggota KSP Dana Jaya Sentosa.</li><li>Mengisi Formulir Simpanan dan menyerahkan copy KTP.</li><li>Besar Simpanan Wirausaha Kelipatan Rp 5.000,-.</li></ul>',
    ],
    [
        'id' => 'simpanan-massa',
        'small_title' => 'SIMPANAN MASSA',
        'img' => 'img-content1.jpg',
        'title' => 'Simpana Massa KSP. DJS adalah produk simpanan dengan konsep arisan modern',
        'description' => '<p>Simpana Massa KSP. DJS adalah produk simpanan dengan konsep arisan modern yang diilhami oleh budaya tradisional Bangsa Indonesia yang didasari semangat gotong-royong dan kekeluargaan. Program Simpanan Massa DJS menjadi salah satu program keuangan inklusif yang terbukti bermanfaat bagi ekonomi di seluruh lapisan, baik ekonomi mikro, kecil, menengah dan atas.</p><ul><li>Peserta Simpanan Massa adalah masyarakat umum.&nbsp;</li><li>Peserta adalah perorangan, dapat mengikuti lebih dari 1 keanggotaan.</li><li>KSP. DJS berhak membatalkan pelaksanaan Program Simpanan Massa apabila&nbsp;Anggota belum memenuhi persyaratan yang telah ditetapkan oleh KSP. DJS.</li><li>Anggota terlebih dulu wajib mendaftarkan diri melalui Surat Pernyataan Keikutsertaan Program.</li><li>Anggita wajib memiliki rekening&nbsp; Simpanan Massa dengan menempatkan dana-nya di rekening tersebut, dan memberikan instruksi kepada KSP. DJS untuk melakukan pemblokiran atas sejumlah dana dalam rekening, berdasarkan Syarat dan Ketentuan Umum Program Simpanan Massa ini.</li><li>Peserta menyetor fotokopi KTP dan mengisi formulir pembukaan Simpanan Massa.</li><li>Peserta simpanan massa terbagi dalam beberapa group.</li><li>Simpanan Massa dimulai saat sudah terbentuk satu group, yaitu 30 orang.</li><li>Apabila pada satu periode Peserta meninggal dunia, maka arisan dapat dilanjutkan oleh ahli waris yang sah untuk selanjutnya menerima benefit arisan yang akan diterima.</li><li>Setoran anggota arisan Rp 1.000.000,- per bulan, selama 30 bulan.</li><li>Program Simpanan Massa diadakan dengan sistem PIAO maximal sebesar 10%, dibuka setiap bulan, pada tanggal 15.</li><li>Uang arisan diserahkan paling lambat 5 hari setelah tanggal 15, setiap bulannya. (apabila bertepatan dengan hari libur) akan dilakukan pada hari berikutnya.</li><li>Dana yang disetorkan tidak dapat ditarik dengan alasan apapun, dan yang akan dibayarkan pada akhir periode arisan, adalah sejumlah dana yang telah disetorkan.</li><li>Setoran arisan paling lambat tanggal 18, setoran langsung ke Teller maupun transfer.</li><li>Apabila dalam satu periode berjalan terjadi perubahan nilai mata uang, maka akan disesuaikan dengan mata uang yang berlaku dan disahkan oleh kebijakan Pemerintah R.I</li><li>Untuk memelihara SOLIDARITAS dan GOTONG ROYONG serta menjaga KEPERCAYAAN sesama anggota dan demi KELANCARAN penyelenggaraan arisan ini, maka diharapkan dengan sangat hormat setiap anggota memenuhi KEWAJIBAN TEPAT WAKTU PEMBAYARAN SESUAI DENGAN KETENTUAN YANG TELAH DITENTUKAN.</li></ul><p>SUKU BUNGA:</p><p>Suku bungan Simpanan Massa, sebesar 0% p.a serta tidak dikenakan biaya administrasi.</p>',
    ],
    [
        'id' => 'simpanan-hari-raya',
        'small_title' => 'SIMPANAN HARI RAYA',
        'img' => 'hari-raya.jpg',
        'title' => 'Raih Kemenangan Idul Fitri dengan Simpanan Hari Raya',
        'description' => '<p><br></p><div class="table-responsive"><table class="table table-bordered"><tbody><tr><td>PAKET&nbsp;</td><td>SETORAN PER HARI&nbsp;</td><td>SALDO TERAKHIR&nbsp;</td><td>PARCEL&nbsp;</td></tr><tr><td>A</td><td>10.000</td><td>3.300.000</td><td>BERAS 1Kg, GULA 1Kg, Minyak1 Lt.</td></tr><tr><td>B</td><td>15.000</td><td>4.950.000</td><td>BERAS 2Kg, GULA 1Kg, Minyak1 Lt.<br></td></tr><tr><td>C</td><td>20.000</td><td>6.600.000</td><td>BERAS 3Kg, GULA 1Kg, Minyak1 Lt.<br></td></tr><tr><td>D</td><td>25.000</td><td>8.250.000</td><td>BERAS 4Kg, GULA 1Kg, Minyak1 Lt.<br></td></tr><tr><td>E</td><td>30.000</td><td>9.900.000</td><td>BERAS 5Kg, GULA 1Kg, Minyak1 Lt.<br></td></tr></tbody></table></div><p>Keterangan:</p><ol><li>PEMBUKA SIMPANAN DIMULAI 01 MEI 2024 S/D 30 JUNI 2024</li><li>SETORAN SIMPANAN DIMULAI 01 MEI 2024 S/D 31 FEBRUARI 2024</li><li>SIMPANAN DIBAGIKAN PADA AWAL PUASA</li><li>UANG DIKEMBALIKAN PENUH DAN TIDAK MENDAPATKAN BUNGA</li><li>SETORAN WAJIB RUTIN SESUAI DENGAN PAKET YANG DIPILIH SAMPAI MENCAPAI MINIMAL SALDO Rp 3.300.000,- DALAM WAKTU 11 BULAN, APABILA SALDO DIBAWAH Rp 3.300.000,- DAN TIDAK RUTIN MAKA TIDAK MENDAPATKAN PARCEL.</li></ol>',
    ],
];
